import Link from 'next/link'
import './globals.css'
import { LoginCom, LogoutCom } from './LoginCom'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'susi',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  return (
    <html>
      <body>
        <nav>
          <Link href="/"><div className='nav-item'>Home</div></Link>
          <Link href="/list"><div className='nav-item'>List</div></Link>
          <Link href="/new"><div className='nav-item'>New Problems</div></Link>
          <div className='nav-item'>{session ? <LogoutCom /> : <LoginCom />}</div>
        </nav>
        {children}
      </body>
    </html>
  )
}
